on:
  pull_request:
jobs:
  mirror_repo:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: step1
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "https://gitlab-master.nvidia.com/api/v4/projects/124577/mirror/pull"
  run_pipeline:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: step1
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "https://gitlab-master.nvidia.com/api/v4/projects/124577/trigger/pipeline"
  
