on:
  pull_request:
jobs:
  trigger_ci:
    environment: GITLAB
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run:  curl -H "Content-Type:application/json" -X POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "${{ secrets.URL }}"
        
      
